trigger: none
pr:
  branches:
    include:
      - main

jobs:
- job: PRLinting
  displayName: 'Linting job for PRs'
  pool:
    vmImage: 'windows-latest'
  steps:
  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: '7.x'
      installationPath: $(Agent.ToolsDirectory)/dotnet

  - script: |
      dotnet tool install -g dotnet-format
      dotnet format --no-restore --verify-no-changes
    displayName: 'Run dotnet format for linting'
    env:
      DOTNET_ROOT: $(Agent.ToolsDirectory)/dotnet

  - script: echo 'Linting successful'
    displayName: 'Linting passed'
